import type { ProviderId } from "../../shared/types";
import type { SelectorSet } from "../shared/dom";

export interface ProviderDomConfig { id: ProviderId; hosts: string[]; selectors: SelectorSet }
export const PROVIDER_DOM_CONFIGS: ProviderDomConfig[] = [
  { id: "chatgpt", hosts: ["chatgpt.com"], selectors: { composer: ["#prompt-textarea", "textarea[placeholder]", "[contenteditable='true'][data-virtualkeyboard='true']"], sendButton: ["button[data-testid='send-button']", "button[aria-label*='Send']"], stopButton: ["button[data-testid='stop-button']", "button[aria-label*='Stop']"], assistantMessages: ["[data-message-author-role='assistant']"], newChatButton: ["a[href='/']", "button[aria-label*='New chat']"], loginIndicator: ["button[data-testid='login-button']", "a[href*='auth/login']"] } },
  { id: "claude", hosts: ["claude.ai"], selectors: { composer: ["div.ProseMirror[contenteditable='true']", "div[contenteditable='true'][role='textbox']", "textarea[placeholder]"], sendButton: ["button[aria-label='Send message']", "button[type='submit']", "button[aria-label*='send' i]", "button[data-testid*='send' i]"], stopButton: ["button[aria-label*='Stop']"], assistantMessages: ["[data-is-streaming]", "[data-testid*='assistant']", ".font-claude-message"], newChatButton: ["a[href='/new']", "button[aria-label*='New chat']"], loginIndicator: ["a[href*='login']", "button[data-testid*='login']"] } },
  { id: "gemini", hosts: ["gemini.google.com"], selectors: { composer: ["rich-textarea [contenteditable='true']", "textarea"], sendButton: ["button[aria-label*='Send message']", "button[aria-label*='Send']"], stopButton: ["button[aria-label*='Stop response']"], assistantMessages: ["message-content", ".model-response-text"], newChatButton: ["a[aria-label*='New chat']"], loginIndicator: ["a[href*='accounts.google.com']"] } },
  { id: "grok", hosts: ["grok.com"], selectors: { composer: ["textarea", "[contenteditable='true']"], sendButton: ["button[aria-label*='Submit']", "button[aria-label*='Send']"], stopButton: ["button[aria-label*='Stop']"], assistantMessages: ["[data-testid*='assistant']", "article"], newChatButton: ["a[href='/']", "button[aria-label*='New']"], loginIndicator: ["a[href*='sign-in']"] } },
  { id: "kimi", hosts: ["kimi.com", "www.kimi.com"], selectors: { composer: ["textarea", "[contenteditable='true'][role='textbox']", "[contenteditable='true']"], sendButton: ["button[aria-label*='send' i]", "button[type='submit']", "button[data-testid*='send' i]", "[role='button'][aria-label*='send' i]"], stopButton: ["button[aria-label*='Stop']"], assistantMessages: ["[data-role='assistant']", "[class*='assistant']"], newChatButton: ["a[href*='/chat']", "button[aria-label*='New']"], loginIndicator: ["a[href*='login']", "button[class*='login']"] } }
];
export function getCurrentProviderConfig(): ProviderDomConfig | undefined { return PROVIDER_DOM_CONFIGS.find((config) => config.hosts.includes(location.hostname)); }
